#!/bin/bash
PROGNAME=$(basename ${0})
function usage() {
    cat<<EOF
$PROGNAME is a tool for making iso of SereneLinux

Usage:
    $PROGNAME [<diskimage>] [version] [<options>]

Example:
    $PROGNAME image.img   19q1.6.5
    $PROGNAME 19q1.6.5
Options:
    --version        print $PROGNAME version
    -h, --help       print this
    -m, --no-umount  no umount when this program is ended
    -w, --workdir    specify where to work directory.
    -p, --mountpoint specify where to mount point.
EOF
}

function printerror() {
    echo -e "$(tput bold)$1$(tput sgr0)\n" 1>&2
    usage
    exit 1
}

function isinstall() {
    if ! type $1 >/dev/null 2>&1; then
    echo "${1} is not installing." 1>&2
    echo "May be you need to install ${2}." 1>&2
    fi
}

## check if not run this as root.
if [ $UID == 0 ]; then
    printerror "You must not run as root."
fi
## check if arguments is typed.
if [[ $# < 1 ]]; then
    printerror "you must type at least one arguments."
fi
## check if depend softwares are installing

isinstall qemu-img qemu
isinstall xhost xorg-xhost
## check if not anything mounted on /mnt
if mountpoint -q /mnt; then
    printerror "anything mounted on /mnt"
fi
## default var
IMAGENAME=/opt/slim/image.img
MOUNTPOINT=/mnt
WORKDIR=/opt/slim/diskimages
## check if arguments is correct
for OPT in "$@"; do
    case "$OPT" in
        '-h'|'--help' )
            usage
            exit 1 ;;
        '--version' )
            echo $PROGNAME 1.00
            exit 1 ;;
        '-m' | '--no-umount' )
            NOUMOUNT=true
            shift 1 ;;
        '-w' | '--workdir' )
            WORKDIR=$2
            shift 2 ;;
        '-p' | '--mountpoint' )
            MOUNTPOINT=$2
            shift 2 ;;
        '-*' )
            echo "Unknown option: $(echo $1 | sed 's/^-*//')" 1>&2
            exit 1 ;;
        *)
            if [[ -n "$1" ]] && [[ ! "$1" =~ ^-+ ]]; then
                if [ -f $1 ]; then
                    IMAGENAME=$1
                    shift 1
                elif [[ $1 =~ [1-9][1-9]q[1-4].[1-9].[1-9] ]]; then
                    VERSION=$1
                    shift 1
                else
                    printerror "Unknown arguments $1"
                fi
            fi ;;
    esac
done
if [[ ! $VERSION == "" ]]; then
    IMAGEPATH=${WORKDIR}/serenelinux_dev_basix_${VERSION}.img
    IMAGENAME=serenelinux_dev_basix_${VERSION}.img
fi
TYPE=${IMAGENAME##*.}
case "$TYPE" in
    "ova" )
        mkdir -p $IMAGENAME.d
        tar xvf $1 -C $IMAGENAME.d
        VMDK=$(ls -m | tr ',' '\n' | grep *.vmdk)
        qemu-img convert -p -f vmdk -O raw $VMDK $IMAGENAME
        rm -rf $IMAGENAME.d ;;

    "vdi" | "vmdk" | "qcow2" | "qed" | "vhd" )
        qemu-img convert -p -f $TYPE -O raw $1 $IMAGENAME ;;
    "img" )
        : ;;
    * )
        printerror "This program supports format formats ova, vdi, vmdk, qcow2, qed, vhd and raw-img.\nIf you want to use excluding that, you must convert this to support format." ;;
esac

exec sudo -E ./slim.sh $WORKDIR $IMAGENAME $MOUNTPOINT $NOUMOUNT
